// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnq2Va35x860bkwEfNjSASQJbkdaNPYe0',
    appId: '1:1015886963575:web:d3bbe8e449e7d4d5fdf772',
    messagingSenderId: '1015886963575',
    projectId: 'twitter-eng-soft-v',
    authDomain: 'twitter-eng-soft-v.firebaseapp.com',
    storageBucket: 'twitter-eng-soft-v.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMbZ3_4npjnLlpKkb_mRqrqKtO7RpjAxU',
    appId: '1:1015886963575:android:07c69c7741072d34fdf772',
    messagingSenderId: '1015886963575',
    projectId: 'twitter-eng-soft-v',
    storageBucket: 'twitter-eng-soft-v.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv6JvlbY6SUR2AAC8UinQYwqInoPS00F4',
    appId: '1:1015886963575:ios:8a7398fb64fb54c3fdf772',
    messagingSenderId: '1015886963575',
    projectId: 'twitter-eng-soft-v',
    storageBucket: 'twitter-eng-soft-v.appspot.com',
    iosClientId: '1015886963575-7as5bfm6sdedj9cpffn6noa99uneies0.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv6JvlbY6SUR2AAC8UinQYwqInoPS00F4',
    appId: '1:1015886963575:ios:8a7398fb64fb54c3fdf772',
    messagingSenderId: '1015886963575',
    projectId: 'twitter-eng-soft-v',
    storageBucket: 'twitter-eng-soft-v.appspot.com',
    iosClientId: '1015886963575-7as5bfm6sdedj9cpffn6noa99uneies0.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterApi',
  );
}
